Param(
    [string]$ProjectRoot = "C:\软件\trader"
)

$ErrorActionPreference = "Stop"

function Ask($prompt, $default = "") {
    if ($default -ne "") {
        $v = Read-Host "$prompt [$default]"
        if ([string]::IsNullOrWhiteSpace($v)) { return $default }
        return $v
    }
    return (Read-Host $prompt)
}

function AskBool($prompt, $default = "n") {
    $v = (Ask $prompt $default).ToLower().Trim()
    return ($v -in @("y","yes","true","1"))
}

function EscapePy([string]$s) {
    if ($null -eq $s) { return "" }
    $t = $s -replace '\\', '\\\\'
    $t = $t -replace '"', '\\"'
    return $t
}

$configPath = Join-Path $ProjectRoot "src\config.py"
if (-not (Test-Path -LiteralPath $configPath)) {
    throw "Config file not found: $configPath"
}

Write-Host "=== Fill EMS config ===" -ForegroundColor Cyan

$dbHost = Ask "MySQL host" "127.0.0.1"
$dbPort = Ask "MySQL port" "3306"
$dbUser = Ask "MySQL user" "ems_user"
$dbPass = Ask "MySQL password"
$dbName = Ask "MySQL database" "trader"

$dingWebhook = Ask "DingTalk webhook (optional)" ""

$apiHost = Ask "API host" "0.0.0.0"
$apiPort = Ask "API port" "18080"
$apiToken = Ask "API token"

$hmacEnabled = AskBool "Enable HMAC auth? (y/n)" "y"
$hmacKeyId = Ask "HMAC key_id" "strategy01"
$hmacSecret = Ask "HMAC secret"
$maxSkew = Ask "HMAC max skew seconds" "300"
$nonceTtl = Ask "Nonce ttl seconds" "300"

$strategyIp = Ask "Strategy public IPs (comma separated, optional)" ""
$ipItems = @()
if (-not [string]::IsNullOrWhiteSpace($strategyIp)) {
    $ipItems = $strategyIp.Split(',') | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" }
}
$ipPy = ($ipItems | ForEach-Object { '"' + (EscapePy $_) + '"' }) -join ", "

$emailEnabled = AskBool "Enable mail ingest? (y/n)" "n"
$emailHost = Ask "IMAP host" "imap.qq.com"
$emailPort = Ask "IMAP port" "993"
$emailUser = Ask "Email username" ""
$emailPass = Ask "Email app password" ""
$emailFolder = Ask "Email folder" "INBOX"
$emailPrefix = Ask "Email subject prefix" "EMS_SIGNAL"
$emailPoll = Ask "Email poll seconds" "15"

$cfg = @"
# -*- coding: utf-8 -*-
"""Global config generated by fill_config.ps1"""

DB_CONFIG = {
    "host": "$(EscapePy $dbHost)",
    "port": $dbPort,
    "user": "$(EscapePy $dbUser)",
    "password": "$(EscapePy $dbPass)",
    "database": "$(EscapePy $dbName)",
    "charset": "utf8mb4",
}

DINGTALK_WEBHOOK = "$(EscapePy $dingWebhook)"

POLL_INTERVAL_SECONDS = 5
MAX_RETRY = 5
BATCH_SIZE = 10
ORDER_WAIT_TIMEOUT = 12
ORDER_POLL_INTERVAL = 1

EMAIL_INGEST_CONFIG = {
    "enabled": $($emailEnabled.ToString().ToLower()),
    "imap_host": "$(EscapePy $emailHost)",
    "imap_port": $emailPort,
    "username": "$(EscapePy $emailUser)",
    "password": "$(EscapePy $emailPass)",
    "folder": "$(EscapePy $emailFolder)",
    "subject_prefix": "$(EscapePy $emailPrefix)",
    "poll_interval_seconds": $emailPoll,
}

API_CONFIG = {
    "host": "$(EscapePy $apiHost)",
    "port": $apiPort,
    "token": "$(EscapePy $apiToken)",
    "ip_whitelist": [$ipPy],
    "hmac_enabled": $($hmacEnabled.ToString().ToLower()),
    "hmac_keys": {
        "$(EscapePy $hmacKeyId)": "$(EscapePy $hmacSecret)",
    },
    "max_skew_seconds": $maxSkew,
    "nonce_ttl_seconds": $nonceTtl,
}
"@

Set-Content -LiteralPath $configPath -Value $cfg -Encoding UTF8
Write-Host "Config written: $configPath" -ForegroundColor Green
