# -*- coding: utf-8 -*-
"""Global config generated by fill_config.ps1"""

DB_CONFIG = {
    "host": "127.0.0.1",
    "port": 3306,
    "user": "root",
    "password": "Qwer!1234567",
    "database": "mydb",
    "charset": "utf8mb4",
}

NOTIFY_MODE = "NONE"  # 鍙€?"NONE", "EMAIL"
SMTP_CONFIG = {
    "host": "",
    "port": 465,
    "user": "",
    "password": "",
    "receivers": [],
}

POLL_INTERVAL_SECONDS = 5
MAX_RETRY = 5
BATCH_SIZE = 10
ORDER_WAIT_TIMEOUT = 12
ORDER_POLL_INTERVAL = 1

EMAIL_INGEST_CONFIG = {
    "enabled": False,
    "imap_host": "imap.qq.com",
    "imap_port": 993,
    "username": "",
    "password": "",
    "folder": "INBOX",
    "subject_prefix": "EMS_SIGNAL",
    "poll_interval_seconds": 15,
}

API_CONFIG = {
    "host": "0.0.0.0",
    "port": 18080,
    "token": "Qwer!1234567",
    "ip_whitelist": ["1.203.161.66","127.0.0.1"],
    "hmac_enabled": True,
    "hmac_keys": {
        "strategy01": "Qwer!1234567",
    },
    "max_skew_seconds": 300,
    "nonce_ttl_seconds": 300,
}
